Responsive
vanegu1tas/vanegas.pro pull request #1
Opened 2020-04-12 01:18 UTC by vanegu1tas

Ajustando el responsive del sitio web

2020-04-12 01:39 UTC, fcor requested changes
Listo, re bien! 🚀 

Yo pondría todas las páginas internas en otra carpeta, como `projects/projectname.html`

Al parecer acá hay un problema con el contenedor de ese texto
![Captura el 2020-04-11 a las 20 38 06](https://user-images.githubusercontent.com/21111451/79058483-61d95c80-7c34-11ea-8ce3-dc38779b11c5.png)

2020-04-12 01:39 UTC, fcor commented on index.html
>    </div>
En la línea 71 sobra `content,`. A menos que necesite la clase content. La coma no se usa ahí entonces al ponerla así, el cree que la clase se llama `content,` y no `content`.

2020-04-12 01:39 UTC, fcor commented on index.html
>        <div class="intro-button">
Las líneas 35 y 36 no están bien indentadas. Podemos configurar Prettier en su VS Code para que le ayude con estas cosas.

2020-04-12 01:39 UTC, fcor commented on css/estilos.css
> +
Falta cerrar esto. Es bueno dejar un espacio entre cada media query y entre cada estilo para que sea fácil ver esto.

2020-04-12 01:39 UTC, fcor commented on +play.html
> +        <button class="contact-button contact-intern"><img src="images/envelope_2709.png" alt="" class="icon-contact"></button>
Póngale siempre el ALT a las imagenes, así sean íconos. Eso le va a ayudar en el puntaje de google.

2020-04-12 01:39 UTC, fcor commented on Lovit.html
> +        <button class="contact-button contact-intern"><img src="images/envelope_2709.png" alt="" class="icon-contact"></button>
ALT

2020-04-12 01:39 UTC, fcor commented on Lovit.html
> +      <img src="images/Flowapp.jpg" alt="" width="100%">
ALT

2020-04-12 01:39 UTC, fcor commented on Lovit.html
> +        <img src="images/f-1.png" alt=""  width="100%">
ALT

2020-04-12 01:39 UTC, fcor commented on +play.html
> +        <img src="images/play-4.png" alt=""  width="100%">
ALT

2020-04-12 01:39 UTC, fcor commented on Trivia.html
> +        <button class="contact-button contact-intern"><img src="images/envelope_2709.png" alt="" class="icon-contact"></button>
ALT

2020-04-12 01:39 UTC, fcor commented on css/estilos.css
>    /* border: 1px solid rgb(255, 19, 235); */
Cuando acabe este branch. Haga un commit de clean up y borre todos los comments.

2020-04-12 01:39 UTC, fcor commented on css/estilos.css
>  @media screen and (max-width: 724px){
Si no lo usa, mejor bórrelo.

2020-04-12 02:31 UTC, vanegu1tas commented on index.html
>    </div>
listo ya borre la coma eso me estaba molestando por que si necesitaba ese estilo

2020-04-16 02:05 UTC, fcor approved these changes

2020-04-20 23:47 UTC, merged